import { defineConfig } from 'vite-plus'

export default defineConfig({
  staged: {
    '*': 'vp check --fix',
  },
  fmt: {
    printWidth: 120,
    singleQuote: true,
    semi: false,
  },
  lint: {
    ignorePatterns: ['packages/docs/**', '**/types.d.ts'],
    options: { typeAware: true, typeCheck: true },
    categories: {
      correctness: 'warn',
      suspicious: 'warn',
    },
    plugins: ['oxc', 'typescript', 'unicorn', 'react', 'jsx-a11y'],
    globals: {
      jest: 'readonly',
      describe: 'readonly',
      it: 'readonly',
      expect: 'readonly',
      beforeEach: 'readonly',
      afterEach: 'readonly',
      beforeAll: 'readonly',
      afterAll: 'readonly',
      test: 'readonly',
      importFile: 'readonly',
      workbenchBase: 'readonly',
      document: 'readonly',
      window: 'readonly',
      navigator: 'readonly',
      console: 'readonly',
    },
    rules: {
      'no-extra-boolean-cast': 'error',
      'no-useless-catch': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'no-const-assign': 'error',
      'no-constant-condition': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-obj-calls': 'error',
      'no-this-before-super': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-undef': 'warn',
      'no-unreachable': 'error',
      'constructor-super': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-vars': 'warn',
      'typescript/no-invalid-void-type': 'warn',
      'react/exhaustive-deps': 'warn',
      'use-isnan': 'error',
      'for-direction': 'error',
      'prefer-const': 'error',
      'unicorn/prefer-node-protocol': 'off',
      'no-async-promise-executor': 'error',
      'no-cond-assign': 'warn',
      'no-ex-assign': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      eqeqeq: 'off',
      'no-duplicate-case': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-keys': 'error',
      'no-empty': 'warn',
      'typescript/no-explicit-any': 'warn',
      'typescript/no-extra-non-null-assertion': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-import-assign': 'error',
      'no-misleading-character-class': 'error',
      'typescript/no-misused-new': 'error',
      'no-prototype-builtins': 'off',
      'no-redeclare': 'error',
      'no-shadow-restricted-names': 'warn',
      'typescript/no-unsafe-declaration-merging': 'error',
      'no-unsafe-negation': 'error',
      'no-var': 'error',
      'no-with': 'error',
      'react/no-array-index-key': 'warn',
      'jsx_a11y/label-has-associated-control': 'warn',
      'react/button-has-type': 'warn',
      'jsx_a11y/no-static-element-interactions': 'warn',
      'jsx_a11y/click-events-have-key-events': 'warn',
      'jsx_a11y/alt-text': 'warn',
      'jsx_a11y/prefer-tag-over-role': 'warn',
      'react/react-in-jsx-scope': 'off',
    },
    overrides: [
      {
        files: [
          'packages/**/*.test.ts',
          'packages/**/*.test.tsx',
          'packages/**/__tests__/**/*.ts',
          'packages/**/__tests__/**/*.tsx',
        ],
        rules: {
          'no-empty': 'off',
          'typescript/no-explicit-any': 'off',
          'no-unused-vars': 'warn',
        },
      },
    ],
  },
})
